# Generated by Django 3.2.6 on 2021-09-21 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(default=0)),
                ('card_set_name', models.CharField(default=None, max_length=100)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_num', models.CharField(default=None, max_length=50)),
                ('card_subset', models.CharField(default=None, max_length=100, null=True)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('card_set_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.cardset')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
            ],
        ),
    ]
