# Generated by Django 3.2.4 on 2021-06-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_subset',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
