# Generated by Django 4.2.16 on 2024-09-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20210922_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_subset',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cardset',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='cardset',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
