# Generated by Django 4.2.16 on 2024-09-17 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('cards', '0004_alter_card_card_subset_alter_cardset_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardListExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('date_entered', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.carduser')),
            ],
        ),
    ]
