# Generated by Django 4.2.16 on 2024-09-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_cardset_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardset',
            name='sport',
            field=models.CharField(default='Baseball', max_length=50, null=True),
        ),
    ]
