# Generated by Django 4.2.16 on 2024-10-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_alter_cardset_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='condition',
            field=models.CharField(blank=True, choices=[('Fair', 'Fair'), ('Good', 'Good'), ('Very Good', 'Very Good'), ('Excellent', 'Excellent'), ('Near Mint', 'Near Mint'), ('Mint', 'Mint')], default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='graded',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
