# Generated by Django 4.2.16 on 2024-10-18 03:49

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_card_condition_card_graded'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='condition',
            field=models.CharField(blank=True, choices=[('Mint', 'Mint'), ('Near Mint', 'Near Mint'), ('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Fair', 'Fair')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cardset',
            name='sport',
            field=models.CharField(choices=[('Baseball', 'Baseball'), ('Football', 'Football'), ('Basketball', 'Basketball')], default='Baseball', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='card',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='cards_card_search__f06ce9_gin'),
        ),
    ]
