# Generated by Django 4.2.16 on 2024-10-27 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_card_search_vector_alter_card_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='slug',
            field=models.SlugField(max_length=250, null=True),
        ),
    ]
