# Generated by Django 4.2.16 on 2024-10-28 17:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_alter_card_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='uu_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
