# Generated by Django 4.2.16 on 2026-10-09 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_remove_card_uu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardset',
            name='year',
            field=models.IntegerField(default=2026),
        ),
    ]
