# Generated by Django 4.2.16 on 2026-10-09 04:08

import cards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_alter_cardset_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardset',
            name='year',
            field=models.IntegerField(default=cards.models.current_year),
        ),
    ]
