# Generated by Django 3.2.4 on 2021-06-27 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_fname', models.CharField(default=None, max_length=50)),
                ('player_lname', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
