# Generated by Django 4.2.16 on 2024-10-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_player_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ignore',
            field=models.BooleanField(default=False),
        ),
    ]
